### ISSUE TITLE
batch() для изменяемых данных

### ISSUE THREAD

**Issue by tsukasa-mixer** [MindyPHP/Mindy_Orm#111]
Возможно имеет смысл сделать параметр или клон функции, для изменяемых данных.

т.е. в том случае когда в процессе итерации происходит изменение обьектов в бд и они более не попадают под выборку.
Для такого случая нам не нужно делать сдвиг в виде offset т.к. если его сделать то часть данных не будет проитерировано.

**Comment by max107** [comment]
Предположим, есть данные ID (0..100).
В процессе итерации по 10 на втором шаге итерации изменились данные 0..5, 15..20. 

Насколько я понимаю, ты предлагаешь на каждый из шагов итерации делать выборку по новой, но в таком случае у тебя на втором шаге итерации при ситуации выше будут попадаться дубликаты записей, которые ты уже обработал.

**Comment by tsukasa-mixer** [comment]
Нет. речь шла когда результаты всей выборки будут изменятся.
Когда предложение было заведено, та реализация выбирала объекты пачками т.е. выбиралось по 10 объектов а следующий запрос изменял лимиты.
Вот и было предложено сделать отдельный бач, или свойство что-бы дать понять что при новой выборке смещения делать не нужно.

А вообще по правильному нужно использовать курсоры.

**Comment by max107** [comment]
@tsukasa-mixer https://github.com/MindyPHP/Mindy_Query/blob/master/src/DataReader.php#L152-L158 они там и используются
